#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Christoph Ungricht"
email = "christoph.ungricht@outlook.com"

[ui]
default-command = "st"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-instructions = false

[colors]
"diff removed token" = { fg = "red", underline = false }
"diff added token" = { fg = "green", underline = false }
"diff modified" = "yellow"
"diff untracked" = "red"
