icons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $icon  {$signal_strength ($ssid on $ip)|Wired connection} "

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
interval = 20
warning = 80.0
alert = 90.0
format = " $icon   $percentage.eng(w:2) ($used / $total) "
[[block.click]]
button = "right"
update = true

[[block]]
block = "memory"
format = " $icon   $mem_used_percents.eng(w:2) ($mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
format = " $icon  {$volume.eng(w:2) |}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "battery"
format = " $icon   $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
full_format = " $icon   $percentage "
charging_format = " $icon   $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
not_charging_format = " $icon   $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
empty_format = " $icon   $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
missing_format = " $icon   Missing "
interval = 10

[[block]]
block = "keyboard_layout"
format = "    $layout $variant "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m %H:%M:%S') "
